name: Build Labor Khata APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Build APK
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "Labor Khata" com.laborkhata.app --web-dir=.
          npx cap add android
          npx cap copy
          cd android
          chmod +x gradlew
         ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Labor-Khata-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
